### ISSUE TITLE
AshGraphql needs to do the right thing regardless of if there is no empty mutations block or not.

### ISSUE THREAD

**Issue by Awlexus** [ash-project/ash_graphql#10]
I defined a resource to join two other resources, but got the following error message. I resolved this, by defining an empty `mutations` block

```elixir
== Compilation error in file lib/myapp_web/graphql/schema.ex ==
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom
    (elixir 1.11.0) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.11.0) lib/enum.ex:169: Enumerable.member?/2
    (elixir 1.11.0) lib/enum.ex:1693: Enum.member?/2
    (elixir 1.11.0) lib/enum.ex:3369: Enum.filter_list/2
    (elixir 1.11.0) lib/enum.ex:3370: Enum.filter_list/2
    (ash_graphql 0.12.0) lib/api/api.ex:51: AshGraphql.Api.mutations/2
    lib/myapp_web/graphql/schema.ex:6: MyApp.DefaultApi.AshTypes.run/2
    (absinthe 1.6.0) lib/absinthe/pipeline.ex:370: Absinthe.Pipeline.run_phase/3
    (absinthe 1.6.0) lib/absinthe/schema.ex:360: Absinthe.Schema.__after_compile__/2
    (stdlib 3.14) lists.erl:1267: :lists.foldl/3
    (stdlib 3.14) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.11.0) lib/kernel/parallel_compiler.ex:314: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/
```

**Comment by zachdaniel** [comment]
For some reason I didn't see this! Thanks for the report, I'll get it fixed

**Comment by zachdaniel** [comment]
There are four scenarios we need to validate:

* no mutations exposed, no empty mutations block <- fine
* mutations exposed, no empty mutations block <- confirmed issues (mutations don't appear in schema)
* no mutations exposed, no empty mutations block <- confirmed issues (graphql playground shows an error in the console, can't load the schema)
* mutations exposed, empty mutations block <- fine
