### ISSUE TITLE
Filtering by an aggregate on a related resource raises an error

### ISSUE THREAD

**Issue by jmayfield74** [ash-project/ash_graphql#207]
Works as expected:
```
listProjects {
    results {
      id
      name
      flow {
        contractSignedCompleted
      }
    }
  }
```

Results in error:
```
listProjects(filter: { flow: { contractSignedCompleted: { eq: true } } }) {
    results {
      id
      name
    }
  }
```
Error:
```
[error] d483efc4-b4ef-4023-97e9-17b09bc73186: Exception raised while resolving query.

** (KeyError) key :name not found in: nil

If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map

    (ash_sql 0.2.29) lib/expr.ex:1619: AshSql.Expr.default_dynamic_expr/6
    (ash_sql 0.2.29) lib/aggregate.ex:138: anonymous fn/7 in AshSql.Aggregate.add_aggregates/6
    (elixir 1.16.1) lib/enum.ex:4842: Enumerable.List.reduce/3
    (elixir 1.16.1) lib/enum.ex:2582: Enum.reduce_while/3
    (ash_sql 0.2.29) lib/aggregate.ex:88: AshSql.Aggregate.add_aggregates/6
    (ash_sql 0.2.29) lib/join.ex:136: anonymous fn/10 in AshSql.Join.join_all_relationships/10
    (elixir 1.16.1) lib/enum.ex:4842: Enumerable.List.reduce/3
    (elixir 1.16.1) lib/enum.ex:2582: Enum.reduce_while/3
    (ash_postgres 2.1.17) lib/data_layer.ex:2885: AshPostgres.DataLayer.filter/4
    (ash 3.3.3) lib/ash/query/query.ex:3106: Ash.Query.maybe_filter/3
    (ash 3.3.3) lib/ash/query/query.ex:2977: Ash.Query.data_layer_query/2
    (ash 3.3.3) lib/ash/actions/read/read.ex:446: anonymous fn/5 in Ash.Actions.Read.do_read/4
    (ash 3.3.3) lib/ash/actions/read/read.ex:786: Ash.Actions.Read.maybe_in_transaction/3
    (ash 3.3.3) lib/ash/actions/read/read.ex:249: Ash.Actions.Read.do_run/3
    (ash 3.3.3) lib/ash/actions/read/read.ex:66: anonymous fn/3 in Ash.Actions.Read.run/3
    (ash 3.3.3) lib/ash/actions/read/read.ex:65: Ash.Actions.Read.run/3
    (ash 3.3.3) lib/ash.ex:1863: Ash.read/2
    (ash_graphql 1.3.1) lib/graphql/resolver.ex:474: AshGraphql.Graphql.Resolver.resolve/2
    (absinthe 1.7.8) lib/absinthe/phase/document/execution/resolution.ex:234: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
    (absinthe 1.7.8) lib/absinthe/phase/document/execution/resolution.ex:189: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/3
```

Project -> flow relationship:
```elixir
    has_many :flow, Projects.Flow do
      public? true
    end
```

Flow -> flow_phase aggregate:
```elixir
    exists :contract_signed_completed, :flow_phase do
      filter expr(phase.slug == "contract-signed" and status == :completed)
      public? true
      filterable? true
    end
```

Flow -> flow_phase relationship:
```elixir
    has_many :flow_phase, Projects.FlowPhase do
      public? true
    end
```

Flow_phase -> phase relationship:
```elixir
    belongs_to :phase, Templates.Phase do
      domain Templates
      allow_nil? false
      public? true
    end
```

- Elixir version: 1.16.1
- Erlang version: 26
- OS: mac sonoma, linux (debian-bullseye)
- Ash version: 3.3.3
- ash_postgres: 2.1.17
- ash_graphql: 1.3.1

**Comment by zachdaniel** [comment]
@jmayfield74 Can you construct the same query without AshGraphql and see if you get the same behavior?

# Something like this:

```elixir
Project
|> Ash.Query.for_read(....)
|> Ash.Query.filter(flow.contract_signed_completed == true)
```

**Comment by zachdaniel** [comment]
Nevermind I've got this reproduced :)
