### ISSUE TITLE
Cryptic warning when generating an input with not fields

### ISSUE THREAD

**Issue by rgraff** [ash-project/ash_graphql#223]
**Describe the bug**
When you have an input resource with no fields, you get a cryptic warning:

```
warning: Embedded type MyApp.SomeUnionType.SomeSubType does not have an input type defined, but is accepted as input in at least one location.
  (ash_graphql 1.3.2) lib/resource/resource.ex:4296: AshGraphql.Resource.do_field_type/5
  (ash_graphql 1.3.2) lib/resource/resource.ex:3293: anonymous fn/4 in AshGraphql.Resource.union_type_definitions/6
  (elixir 1.17.2) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
  (ash_graphql 1.3.2) lib/resource/resource.ex:3287: AshGraphql.Resource.union_type_definitions/6
  (elixir 1.17.2) lib/enum.ex:4353: Enum.flat_map_list/2
  (elixir 1.17.2) lib/enum.ex:4354: Enum.flat_map_list/2
```

**To Reproduce**
In my particular instance, I was scaffolding out a new UnionType and its various SubTypes but I hadn't defined any attributes yet and had an empty `accepts`

**Expected behavior**
A warning that says it can't define an input type without at least one input attribute.

\*\* Runtime

- Elixir version
- Erlang version
- OS
- Ash version
- any related extension versions

**Additional context**

**Comment by RhettPoole** [comment]
I'm working on this now

**Comment by RhettPoole** [comment]
My strategy to fix this issue is as follows: I’ll reproduce the issue by creating a minimal embedded resource with no accepted input fields and a parent resource that uses it as input. I’ll then update the warning in `lib/resource/resource.ex` to clearly explain that no GraphQL input fields were produced, why it falls back to JSON, and what the user should check. I’ll add a focused test to verify the new warning text.

**Comment by zachdaniel** [comment]
Sounds good!
